---
title: "Review Demo"
output: html_document
date: "2023-10-09"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
install.packages("httr")
install.packages("jsonlite")
install.packages("dataRetrieval")
```

```{r}
library(tidyverse)
library(rstatix)

# new packages! Only if you want to work through the data retrieval process
library(httr)
library(jsonlite)
library(dataRetrieval)
```

Pull data from USGS

```{r}
# pulls USGS daily ('dv') stream flow data for those two sites:
usgs <- readNWISdv(siteNumbers = c("06752260", "06752280"), # USGS site code for the Poudre River at the Lincoln Bridge and the ELC
                                  parameterCd = "00060", # USGS code for stream flow
                                  startDate = "2020-10-01", # YYYY-MM-DD formatting
                                  endDate = "2023-10-01") %>% # YYYY-MM-DD formatting
  rename(q_cfs = X_00060_00003) %>% # USGS code for stream flow units in cubic feet per second (CFS)
  mutate(Date = lubridate::ymd(Date), # convert the Date column to "Date" formatting using the `lubridate` package
         Site = case_when(site_no == "06752260" ~ "Lincoln", 
                          site_no == "06752280" ~ "Boxelder")) 

# if you want to save the data:
#write_csv(usgs, 'data/review-usgs.csv')
```

Pull data from CDWR API

Write function:

```{r}
# Functin to retrieve data
co_water_data <- function(site, start_year, end_year){
  
  raw_data <- httr::GET(url = paste0("https://dwr.state.co.us/Rest/GET/api/v2/surfacewater/surfacewatertsday/?format=json&dateFormat=dateOnly&fields=abbrev%2CmeasDate%2Cvalue%2CmeasUnit&encoding=deflate&abbrev=",site,
                                     "&min-measDate=10%2F01%2F", start_year,
                                     "&max-measDate=09%2F30%2F", end_year))
  
  # extract the text data, returns a JSON object
  extracted_data <- httr::content(raw_data, as = "text", encoding = "UTF-8") 
  
  # parse text from JSON to data frame
  final_data <- jsonlite::fromJSON(extracted_data)[["ResultList"]]
  
  return(final_data)
  
}
```

Map API call function over our CDWR sites

```{r}
# run function for our two sites
sites <- c("CLAFTCCO","CLARIVCO")

cdwr <-  
  map_dfr(sites, ~ co_water_data(site = .x, start_year = 2020, end_year = 2023))
 
# If you want to save this file
#write_csv(cdwr, 'data/review-cdwr.csv') 
```

OR READ in .csv on Canvas

```{r}
usgs <- read_csv('data/review-usgs.csv')

cdwr <- read_csv('data/review-cdwr.csv') 
```

Inspect out data frames

```{r}
glimpse(cdwr)

glimpse(usgs)
```

Clean CDWR so we can bind with the USGS data

```{r}
cdwr_clean <- cdwr %>% 
  rename(q_cfs = value) %>%
  mutate(Date = ymd(measDate),
         agency_cd = "CDWR",
         Site = case_when(abbrev == "CLAFTCCO" ~ "Canyon",
                          abbrev == "CLARIVCO" ~ "Timnath"))
  
```

Bind with USGS

```{r}
data <- bind_rows(usgs, cdwr_clean) %>% 
  select(agency_cd, Site, Date, q_cfs)
```

Explore the data

```{r}
data %>% 
  mutate(Site = fct(Site, levels = c("Canyon", "Lincoln", "Boxelder", "Timnath"))) %>% 
  ggplot(aes(x = Date, y = q_cfs)) +
  geom_line() +
  facet_wrap(~Site, ncol = 1)
```

Clean and visualize among years

```{r}
data_annual <- data %>% 
  separate(Date, sep = "-", into = c("Year", "Month", "Day")) %>% 
  group_by(Year, Month, Site) %>% 
  summarise(monthly_q = mean(q_cfs))
```

Visualize:

```{r}
data_annual %>% 
  ggplot(aes(x = Month, y = monthly_q, group = Year))+
  geom_line(aes(color = Year)) +
  facet_wrap(~Site, ncol = 1)
  
```

\
Calculate downstream differences in streamflow

```{r}
data_dif <- data %>% 
  select(Site, Date, q_cfs) %>% 
  pivot_wider( names_from = Site, values_from = q_cfs) %>% 
  mutate_at(c("Lincoln", "Boxelder", "Timnath"), .funs =  ~ (Canyon - .x)) %>% 
  pivot_longer(-c(Canyon, Date))
```

Visualize

```{r}
data_dif %>% 
  mutate(name = fct(name, levels = c("Lincoln", "Boxelder", "Timnath"))) %>% 
  ggplot() +
    geom_line(aes(x = Date, y = value, color = name)) +
    theme_bw() +
    facet_wrap("name")+
    ylab("Streamflow Difference from Poudre Mouth")
```
