<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title> 7 Correlation and simple linear regression | Introduction to Data Analysis in R</title>
  <meta name="description" content="This site hosts the course content for WR 696 at Colorado State University." />
  <meta name="generator" content="bookdown 0.35 and GitBook 2.6.7" />

  <meta property="og:title" content=" 7 Correlation and simple linear regression | Introduction to Data Analysis in R" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This site hosts the course content for WR 696 at Colorado State University." />
  <meta name="github-repo" content="rossyndicate/WR696_R_Intro" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content=" 7 Correlation and simple linear regression | Introduction to Data Analysis in R" />
  
  <meta name="twitter:description" content="This site hosts the course content for WR 696 at Colorado State University." />
  

<meta name="author" content="Caitlin C. Mothes, PhD and Katie Willi" />


<meta name="date" content="2023-09-24" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="data-analysis-t-test-and-anova.html"/>
<link rel="next" href="multiple-linear-regression-mlr.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/htmlwidgets-1.6.2/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.10.2/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.2.0/css/crosstalk.min.css" rel="stylesheet" />
<script src="libs/crosstalk-1.2.0/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-2.11.1/plotly-latest.min.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Introduction to Data Analysis in R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Welcome!</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#set-up-instructions"><i class="fa fa-check"></i>Set up Instructions</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#navigating-this-site"><i class="fa fa-check"></i>Navigating this site</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#goals"><i class="fa fa-check"></i>Goals</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#approach-and-expectations"><i class="fa fa-check"></i>Approach and Expectations</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#class-schedule"><i class="fa fa-check"></i>Class Schedule</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#additional-introductory-resources"><i class="fa fa-check"></i>Additional introductory resources</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="setup-instructions.html"><a href="setup-instructions.html"><i class="fa fa-check"></i><b>2</b> Setup Instructions</a>
<ul>
<li class="chapter" data-level="2.1" data-path="setup-instructions.html"><a href="setup-instructions.html#install-r-and-rstudio"><i class="fa fa-check"></i><b>2.1</b> Install R and RStudio</a></li>
<li class="chapter" data-level="2.2" data-path="setup-instructions.html"><a href="setup-instructions.html#package-installation"><i class="fa fa-check"></i><b>2.2</b> Package Installation</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="introduction-to-r-rstudio-and-r-markdown.html"><a href="introduction-to-r-rstudio-and-r-markdown.html"><i class="fa fa-check"></i><b>3</b> Introduction to R, RStudio and R Markdown</a>
<ul>
<li class="chapter" data-level="3.1" data-path="introduction-to-r-rstudio-and-r-markdown.html"><a href="introduction-to-r-rstudio-and-r-markdown.html#getting-to-know-rstudio"><i class="fa fa-check"></i><b>3.1</b> Getting to know RStudio</a></li>
<li class="chapter" data-level="3.2" data-path="introduction-to-r-rstudio-and-r-markdown.html"><a href="introduction-to-r-rstudio-and-r-markdown.html#r-projects"><i class="fa fa-check"></i><b>3.2</b> R Projects</a></li>
<li class="chapter" data-level="3.3" data-path="introduction-to-r-rstudio-and-r-markdown.html"><a href="introduction-to-r-rstudio-and-r-markdown.html#write-a-set-up-script"><i class="fa fa-check"></i><b>3.3</b> Write a set-up script</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="introduction-to-r-rstudio-and-r-markdown.html"><a href="introduction-to-r-rstudio-and-r-markdown.html#functions"><i class="fa fa-check"></i><b>3.3.1</b> Functions</a></li>
<li class="chapter" data-level="3.3.2" data-path="introduction-to-r-rstudio-and-r-markdown.html"><a href="introduction-to-r-rstudio-and-r-markdown.html#packages"><i class="fa fa-check"></i><b>3.3.2</b> Packages</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="introduction-to-r-rstudio-and-r-markdown.html"><a href="introduction-to-r-rstudio-and-r-markdown.html#r-markdown"><i class="fa fa-check"></i><b>3.4</b> R Markdown</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="introduction-to-r-rstudio-and-r-markdown.html"><a href="introduction-to-r-rstudio-and-r-markdown.html#what-about-quarto"><i class="fa fa-check"></i><b>3.4.1</b> What About Quarto?</a></li>
<li class="chapter" data-level="3.4.2" data-path="introduction-to-r-rstudio-and-r-markdown.html"><a href="introduction-to-r-rstudio-and-r-markdown.html#getting-started-with-r-markdown"><i class="fa fa-check"></i><b>3.4.2</b> Getting started with R Markdown</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="introduction-to-r-rstudio-and-r-markdown.html"><a href="introduction-to-r-rstudio-and-r-markdown.html#explore"><i class="fa fa-check"></i><b>3.5</b> Explore</a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="introduction-to-r-rstudio-and-r-markdown.html"><a href="introduction-to-r-rstudio-and-r-markdown.html#the-penguins-data"><i class="fa fa-check"></i><b>3.5.1</b> The <code>penguins</code> data</a></li>
<li class="chapter" data-level="3.5.2" data-path="introduction-to-r-rstudio-and-r-markdown.html"><a href="introduction-to-r-rstudio-and-r-markdown.html#data-types"><i class="fa fa-check"></i><b>3.5.2</b> Data Types</a></li>
<li class="chapter" data-level="3.5.3" data-path="introduction-to-r-rstudio-and-r-markdown.html"><a href="introduction-to-r-rstudio-and-r-markdown.html#indexing"><i class="fa fa-check"></i><b>3.5.3</b> Indexing</a></li>
<li class="chapter" data-level="3.5.4" data-path="introduction-to-r-rstudio-and-r-markdown.html"><a href="introduction-to-r-rstudio-and-r-markdown.html#the-dplyr-package"><i class="fa fa-check"></i><b>3.5.4</b> The {dplyr} package</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="introduction-to-r-rstudio-and-r-markdown.html"><a href="introduction-to-r-rstudio-and-r-markdown.html#read-and-write-data"><i class="fa fa-check"></i><b>3.6</b> Read and Write Data</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html"><i class="fa fa-check"></i><b>4</b> Exploratory Data Analysis</a>
<ul>
<li class="chapter" data-level="4.0.1" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#the-penguins-data-1"><i class="fa fa-check"></i><b>4.0.1</b> The <code>penguins</code> data</a></li>
<li class="chapter" data-level="4.0.2" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#exploratory-data-analysis-1"><i class="fa fa-check"></i><b>4.0.2</b> Exploratory Data Analysis</a></li>
<li class="chapter" data-level="4.1" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#data-wrangling"><i class="fa fa-check"></i><b>4.1</b> Data wrangling</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#the-dplyr-package-1"><i class="fa fa-check"></i><b>4.1.1</b> The <code>dplyr</code> package</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#exercises-2"><i class="fa fa-check"></i><b>4.2</b> Exercises</a></li>
<li class="chapter" data-level="4.3" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#visualization"><i class="fa fa-check"></i><b>4.3</b> Visualization</a></li>
<li class="chapter" data-level="4.4" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#exercises-3"><i class="fa fa-check"></i><b>4.4</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="data-visualization-in-r.html"><a href="data-visualization-in-r.html"><i class="fa fa-check"></i><b>5</b> Data Visualization in R</a>
<ul>
<li class="chapter" data-level="5.0.1" data-path="data-visualization-in-r.html"><a href="data-visualization-in-r.html#data-preparation"><i class="fa fa-check"></i><b>5.0.1</b> Data Preparation</a></li>
<li class="chapter" data-level="5.1" data-path="data-visualization-in-r.html"><a href="data-visualization-in-r.html#publication-ready-figures-with-ggplot2"><i class="fa fa-check"></i><b>5.1</b> Publication Ready Figures with <code>ggplot2</code></a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="data-visualization-in-r.html"><a href="data-visualization-in-r.html#general-appearance"><i class="fa fa-check"></i><b>5.1.1</b> General Appearance</a></li>
<li class="chapter" data-level="5.1.2" data-path="data-visualization-in-r.html"><a href="data-visualization-in-r.html#color-size-and-legends"><i class="fa fa-check"></i><b>5.1.2</b> Color, Size and Legends</a></li>
<li class="chapter" data-level="5.1.3" data-path="data-visualization-in-r.html"><a href="data-visualization-in-r.html#annotation"><i class="fa fa-check"></i><b>5.1.3</b> Annotation</a></li>
<li class="chapter" data-level="5.1.4" data-path="data-visualization-in-r.html"><a href="data-visualization-in-r.html#finalize-and-save"><i class="fa fa-check"></i><b>5.1.4</b> Finalize and save</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="data-visualization-in-r.html"><a href="data-visualization-in-r.html#the-assignment"><i class="fa fa-check"></i><b>5.2</b> The Assignment</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="data-visualization-in-r.html"><a href="data-visualization-in-r.html#acknowledgements-and-resources"><i class="fa fa-check"></i><b>5.2.1</b> Acknowledgements and Resources</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="data-analysis-t-test-and-anova.html"><a href="data-analysis-t-test-and-anova.html"><i class="fa fa-check"></i><b>6</b> Data Analysis: T-test and ANOVA</a>
<ul>
<li class="chapter" data-level="6.1" data-path="data-analysis-t-test-and-anova.html"><a href="data-analysis-t-test-and-anova.html#explore-the-dataset"><i class="fa fa-check"></i><b>6.1</b> Explore the dataset</a></li>
<li class="chapter" data-level="6.2" data-path="data-analysis-t-test-and-anova.html"><a href="data-analysis-t-test-and-anova.html#t-test---compare-two-means"><i class="fa fa-check"></i><b>6.2</b> t-test - Compare two means</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="data-analysis-t-test-and-anova.html"><a href="data-analysis-t-test-and-anova.html#assumptions"><i class="fa fa-check"></i><b>6.2.1</b> Assumptions</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="data-analysis-t-test-and-anova.html"><a href="data-analysis-t-test-and-anova.html#anova-test---compare-more-than-two-means"><i class="fa fa-check"></i><b>6.3</b> ANOVA test - compare more than two means</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="data-analysis-t-test-and-anova.html"><a href="data-analysis-t-test-and-anova.html#assumptions-1"><i class="fa fa-check"></i><b>6.3.1</b> Assumptions</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="data-analysis-t-test-and-anova.html"><a href="data-analysis-t-test-and-anova.html#exercises-4"><i class="fa fa-check"></i><b>6.4</b> Exercises</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="data-analysis-t-test-and-anova.html"><a href="data-analysis-t-test-and-anova.html#acknowledgements"><i class="fa fa-check"></i><b>6.4.1</b> Acknowledgements</a></li>
<li class="chapter" data-level="6.4.2" data-path="data-analysis-t-test-and-anova.html"><a href="data-analysis-t-test-and-anova.html#citations"><i class="fa fa-check"></i><b>6.4.2</b> Citations</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="correlation-and-simple-linear-regression.html"><a href="correlation-and-simple-linear-regression.html"><i class="fa fa-check"></i><b>7</b> Correlation and simple linear regression</a>
<ul>
<li class="chapter" data-level="7.1" data-path="correlation-and-simple-linear-regression.html"><a href="correlation-and-simple-linear-regression.html#correlation-with-salamanders"><i class="fa fa-check"></i><b>7.1</b> Correlation with salamanders</a></li>
<li class="chapter" data-level="7.2" data-path="correlation-and-simple-linear-regression.html"><a href="correlation-and-simple-linear-regression.html#simple-linear-regression-with-crabs"><i class="fa fa-check"></i><b>7.2</b> Simple linear regression with crabs</a></li>
<li class="chapter" data-level="7.3" data-path="correlation-and-simple-linear-regression.html"><a href="correlation-and-simple-linear-regression.html#assignment"><i class="fa fa-check"></i><b>7.3</b> Assignment:</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="multiple-linear-regression-mlr.html"><a href="multiple-linear-regression-mlr.html"><i class="fa fa-check"></i><b>8</b> Multiple linear regression (MLR)</a>
<ul>
<li class="chapter" data-level="8.1" data-path="multiple-linear-regression-mlr.html"><a href="multiple-linear-regression-mlr.html#mlr-in-r"><i class="fa fa-check"></i><b>8.1</b> MLR in R</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="multiple-linear-regression-mlr.html"><a href="multiple-linear-regression-mlr.html#predicting-crab-size-1"><i class="fa fa-check"></i><b>8.1.1</b> Predicting crab size</a></li>
<li class="chapter" data-level="8.1.2" data-path="multiple-linear-regression-mlr.html"><a href="multiple-linear-regression-mlr.html#mlr-assumptions"><i class="fa fa-check"></i><b>8.1.2</b> MLR Assumptions</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="multiple-linear-regression-mlr.html"><a href="multiple-linear-regression-mlr.html#assignment-1"><i class="fa fa-check"></i><b>8.2</b> Assignment</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="multiple-linear-regression-mlr.html"><a href="multiple-linear-regression-mlr.html#download-the-usgs-folder-on-canvas-and-store-it-in-a-data-folder-in-this-assignments-project-directory.-here-is-a-list-of-all-of-these-files"><i class="fa fa-check"></i><b>8.2.1</b> Download the ‘usgs’ folder on Canvas and store it in a “data” folder in this assignment’s project directory. Here is a list of all of these files:</a></li>
<li class="chapter" data-level="8.2.2" data-path="multiple-linear-regression-mlr.html"><a href="multiple-linear-regression-mlr.html#read-in-each-of-the-data-sets-associated-with-the-assignment-and-combine-them-into-a-single-data-set.-hint-what-does-map_dfr-do"><i class="fa fa-check"></i><b>8.2.2</b> Read in each of the data sets associated with the assignment and combine them into a single data set. (HINT: What does map_dfr() do?)</a></li>
<li class="chapter" data-level="8.2.3" data-path="multiple-linear-regression-mlr.html"><a href="multiple-linear-regression-mlr.html#using-our-combined-data-set-plot-each-variable-against-mean-annual-stream-flow-to-identify-variables-that-seem-to-have-a-linear-relationship-with-stream-flow."><i class="fa fa-check"></i><b>8.2.3</b> Using our combined data set, plot each variable against mean annual stream flow to identify variables that seem to have a linear relationship with stream flow.</a></li>
<li class="chapter" data-level="8.2.4" data-path="multiple-linear-regression-mlr.html"><a href="multiple-linear-regression-mlr.html#develop-a-multiple-linear-regression-model-using-any-combination-of-the-variables-in-the-data-set.-what-is-your-r-squared-value-which-of-your-variables-if-any-are-significant-predictors-of-stream-flow"><i class="fa fa-check"></i><b>8.2.4</b> Develop a multiple linear regression model using any combination of the variables in the data set. What is your R-squared value? Which of your variables (if any) are significant predictors of stream flow?</a></li>
<li class="chapter" data-level="8.2.5" data-path="multiple-linear-regression-mlr.html"><a href="multiple-linear-regression-mlr.html#check-to-see-if-your-model-meets-the-model-assumptions-required-for-mlr."><i class="fa fa-check"></i><b>8.2.5</b> Check to see if your model meets the model assumptions required for MLR.</a></li>
<li class="chapter" data-level="8.2.6" data-path="multiple-linear-regression-mlr.html"><a href="multiple-linear-regression-mlr.html#use-your-model-to-predict-mean-annual-stream-flow-for-two-new-sets-of-predictor-data."><i class="fa fa-check"></i><b>8.2.6</b> Use your model to predict mean annual stream flow for two new sets of predictor data.</a></li>
<li class="chapter" data-level="8.2.7" data-path="multiple-linear-regression-mlr.html"><a href="multiple-linear-regression-mlr.html#if-your-model-does-not-meet-the-models-assumptions-what-are-some-ways-of-manipulating-the-data-set-so-that-it-might-hint-review-chapter-6"><i class="fa fa-check"></i><b>8.2.7</b> If your model does not meet the model’s assumptions, what are some ways of manipulating the data set so that it might? (HINT: review chapter 6)</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Introduction to Data Analysis in R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="correlation-and-simple-linear-regression" class="section level1 hasAnchor" number="7">
<h1><span class="header-section-number"> 7</span> Correlation and simple linear regression<a href="correlation-and-simple-linear-regression.html#correlation-and-simple-linear-regression" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div class="sourceCode" id="cb145"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb145-1"><a href="correlation-and-simple-linear-regression.html#cb145-1" tabindex="-1"></a><span class="co"># load in packages</span></span>
<span id="cb145-2"><a href="correlation-and-simple-linear-regression.html#cb145-2" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb145-3"><a href="correlation-and-simple-linear-regression.html#cb145-3" tabindex="-1"></a><span class="fu">library</span>(lterdatasampler)</span>
<span id="cb145-4"><a href="correlation-and-simple-linear-regression.html#cb145-4" tabindex="-1"></a><span class="fu">library</span>(rstatix)</span>
<span id="cb145-5"><a href="correlation-and-simple-linear-regression.html#cb145-5" tabindex="-1"></a><span class="fu">library</span>(lubridate) <span class="co"># THIS IS A NEW ONE FOR Y&#39;ALL!</span></span></code></pre></div>
<div id="correlation-with-salamanders" class="section level2 hasAnchor" number="7.1">
<h2><span class="header-section-number">7.1</span> Correlation with salamanders<a href="correlation-and-simple-linear-regression.html#correlation-with-salamanders" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Correlation measures the strength and direction of a relationship between <strong>two continuous variables</strong>. The key result of a correlation test, the correlation coefficient (<em>r</em>), ranges from -1 to +1, with 0 indicating no linear relationship, -1 a perfect negative relationship and 1 indicating a perfect positive relationship.</p>
<p>We will use the <code>and_vertebrates</code> data set to demonstrate the correlation test; we can test our length and weight continuous variables to see if “long” salamanders also weigh more.</p>
<p>First, we’ll need to clean our data set to just include salamanders, and remove missing values for length and weight. Let’s focus on the variable <code>length_2_mm</code> for snout-to-tail length.</p>
<div class="sourceCode" id="cb146"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb146-1"><a href="correlation-and-simple-linear-regression.html#cb146-1" tabindex="-1"></a><span class="fu">data</span>(<span class="st">&quot;and_vertebrates&quot;</span>)</span>
<span id="cb146-2"><a href="correlation-and-simple-linear-regression.html#cb146-2" tabindex="-1"></a></span>
<span id="cb146-3"><a href="correlation-and-simple-linear-regression.html#cb146-3" tabindex="-1"></a>sal <span class="ot">&lt;-</span> and_vertebrates <span class="sc">%&gt;%</span> </span>
<span id="cb146-4"><a href="correlation-and-simple-linear-regression.html#cb146-4" tabindex="-1"></a>  <span class="co"># find observations that contain the string &quot;salamander&quot; in the species column:</span></span>
<span id="cb146-5"><a href="correlation-and-simple-linear-regression.html#cb146-5" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">grepl</span>(<span class="st">&quot;salamander&quot;</span>, species)) <span class="sc">%&gt;%</span></span>
<span id="cb146-6"><a href="correlation-and-simple-linear-regression.html#cb146-6" tabindex="-1"></a>  <span class="fu">drop_na</span>(length_2_mm, weight_g)</span></code></pre></div>
<div id="eda" class="section level4 hasAnchor" number="7.1.0.1">
<h4><span class="header-section-number">7.1.0.1</span> EDA<a href="correlation-and-simple-linear-regression.html#eda" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Before diving in, let’s visually explore the relationship between our two variables with a scatter plot:</p>
<div class="sourceCode" id="cb147"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb147-1"><a href="correlation-and-simple-linear-regression.html#cb147-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> sal) <span class="sc">+</span> </span>
<span id="cb147-2"><a href="correlation-and-simple-linear-regression.html#cb147-2" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x =</span> length_2_mm, <span class="at">y =</span> weight_g)) <span class="sc">+</span></span>
<span id="cb147-3"><a href="correlation-and-simple-linear-regression.html#cb147-3" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<p><img src="06-corr-slr_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<p>From our plot, we see that there is indeed a pretty visible relationship between a salamander’s weight and length. In other words, a salamander’s weight and length seem to be <strong>positively correlated:</strong> as length increases, weight also increases, and vice versa. Moreover, this relationship does not appear linear. And, we will need to see what the distribution of our variables looks like:</p>
<div class="sourceCode" id="cb148"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb148-1"><a href="correlation-and-simple-linear-regression.html#cb148-1" tabindex="-1"></a><span class="fu">hist</span>(sal<span class="sc">$</span>length_2_mm) <span class="co"># skewed... is it technically &quot;normal&quot; distribution?</span></span></code></pre></div>
<p><img src="06-corr-slr_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<div class="sourceCode" id="cb149"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb149-1"><a href="correlation-and-simple-linear-regression.html#cb149-1" tabindex="-1"></a><span class="fu">hist</span>(sal<span class="sc">$</span>weight_g) <span class="co"># def non normal distribution</span></span></code></pre></div>
<p><img src="06-corr-slr_files/figure-html/unnamed-chunk-4-2.png" width="672" /></p>
<p>They both look pretty skewed, therefore likely not normally distributed. We can statistically test if a variable fits a normal distribution with the <code>shapiro.test()</code> function. However, this function only runs for 5000 observations or less. Thereofore, we will need to test for normality on a random subset of our full data set:</p>
<div class="sourceCode" id="cb150"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb150-1"><a href="correlation-and-simple-linear-regression.html#cb150-1" tabindex="-1"></a>sal_sub <span class="ot">&lt;-</span> sal <span class="sc">%&gt;%</span> <span class="fu">slice_sample</span>(<span class="at">n =</span> <span class="dv">5000</span>) </span>
<span id="cb150-2"><a href="correlation-and-simple-linear-regression.html#cb150-2" tabindex="-1"></a>  </span>
<span id="cb150-3"><a href="correlation-and-simple-linear-regression.html#cb150-3" tabindex="-1"></a><span class="fu">shapiro.test</span>(sal_sub<span class="sc">$</span>length_2_mm)</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  sal_sub$length_2_mm
## W = 0.93124, p-value &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb152"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb152-1"><a href="correlation-and-simple-linear-regression.html#cb152-1" tabindex="-1"></a><span class="fu">shapiro.test</span>(sal_sub<span class="sc">$</span>weight_g)</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  sal_sub$weight_g
## W = 0.55866, p-value &lt; 2.2e-16</code></pre>
<p>The <em>null hypothesis of the Shapiro-Wilk normality test is that the variable is normally distributed</em>, so a p-value less than 0.05, at 95% confidence (as we see for both of our variables here) tells use that our data does not fit a normal distribution.</p>
<p>Therefore we have two options as we did with our t-test example in the previous lesson: transform the variables or use a non-parametric test. Here, we will go ahead with a non-parametric Spearman correlation test.</p>
</div>
<div id="correlation-test-in-r" class="section level4 hasAnchor" number="7.1.0.2">
<h4><span class="header-section-number">7.1.0.2</span> Correlation test in R<a href="correlation-and-simple-linear-regression.html#correlation-test-in-r" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>In R, we can perform this correlation test using the {rstatix}’s <code>cor_test()</code> function:</p>
<div class="sourceCode" id="cb154"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb154-1"><a href="correlation-and-simple-linear-regression.html#cb154-1" tabindex="-1"></a><span class="fu">cor_test</span>(sal,</span>
<span id="cb154-2"><a href="correlation-and-simple-linear-regression.html#cb154-2" tabindex="-1"></a>         <span class="at">vars =</span> <span class="fu">c</span>(length_2_mm, weight_g), <span class="co"># vector of continuous vars we want to test</span></span>
<span id="cb154-3"><a href="correlation-and-simple-linear-regression.html#cb154-3" tabindex="-1"></a>         <span class="at">alternative =</span> <span class="st">&quot;two.sided&quot;</span>, <span class="co"># we want to test both positive and negative corr.</span></span>
<span id="cb154-4"><a href="correlation-and-simple-linear-regression.html#cb154-4" tabindex="-1"></a>         <span class="at">method =</span> <span class="st">&quot;spearman&quot;</span>) <span class="co"># spearman is for non-parametric corr. method</span></span></code></pre></div>
<pre><code>## # A tibble: 1 × 6
##   var1        var2       cor  statistic     p method  
##   &lt;chr&gt;       &lt;chr&gt;    &lt;dbl&gt;      &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;   
## 1 length_2_mm weight_g  0.98 820565131.     0 Spearman</code></pre>
<p><strong><code>cor</code></strong> is the correlation coefficient, <em>r</em>. In this example it is positive, indicating that there is a positive correlation between weight and length. Remember that <em>r</em> can only range from -1 to +1. So, a value of 0.98 indicates a very strong relationship.</p>
<p><code>statistic</code> is the test statistic (t) which is calculated using <em>r</em> and the number of observations in the test.</p>
<p><code>p</code> is the p-value. Here, it is calculated using the confidence level and the test statistic.</p>
<div class="alert alert-info">
<p>When two continuous variables are normally distributed and appear to have a linear relationship, one should use the <em>Pearson correlation test</em>.</p>
</div>
</div>
<div id="correlation-limitations" class="section level4 hasAnchor" number="7.1.0.3">
<h4><span class="header-section-number">7.1.0.3</span> <strong>Correlation limitations</strong><a href="correlation-and-simple-linear-regression.html#correlation-limitations" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Using a correlation test, we identified that a salamander’s weight and its length have a positive relationship. But, our conclusions have to stop there: all we can deduce from a correlation test is whether or not a relationship exists. There is no information about which one leads to the other (i.e., causality), and there is no information about how we might be able to predict one from the other.</p>
</div>
</div>
<div id="simple-linear-regression-with-crabs" class="section level2 hasAnchor" number="7.2">
<h2><span class="header-section-number">7.2</span> Simple linear regression with crabs<a href="correlation-and-simple-linear-regression.html#simple-linear-regression-with-crabs" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In the summer of 2016, researchers surveyed fiddler crabs for their size across the Atlantic coast - from Florida to Massachusetts. Additional information about where the crabs lived (including coordinates, air, and water temperature) was also provided. Because we have size data across multiple climates, this study provides an excellent data set to test Bergmann’s rule.</p>
<p>With this data set, we can broadly assume that the further north we go, the colder the climate. Therefore, let’s use latitude as our variable to represent “coldness”, with an increase in latitude representing cooler climate conditions, to explore the relationship between crab size and climate.</p>
<p>Taking correlation a step further, simple linear regression allows us to describe the relationship between two continuous, linearly-related variables. This description comes in the form of an equation that produces a line of best fit through our variables plotted against each other. Using that line, we can then predict a new crab’s size based on its location, and vice versa.</p>
<p>But first we must define which variable leads to the other’s change, something we didn’t really need to think about for correlation. Based on Bergmann’s rule, we know that the cooler climate leads to increased size, so our explanatory variable (<em>x</em>) will be latitude, and our response variable (<em>y</em>) will be crab size. There are a few ways to describe this relationship between latitude and size in the statistics lexicon:</p>
<table>
<tbody>
<tr class="odd">
<td><strong>X Variable (Crab Latitude)</strong></td>
<td><strong>Y Variable (Crab Size)</strong></td>
</tr>
<tr class="even">
<td>Cause (what changes)</td>
<td>Effect (outcome of that change)</td>
</tr>
<tr class="odd">
<td>Independent</td>
<td>Dependent</td>
</tr>
<tr class="even">
<td>Predictor</td>
<td>Outcome</td>
</tr>
<tr class="odd">
<td>Explanatory</td>
<td>Response</td>
</tr>
</tbody>
</table>
<p>Let’s first visualize latitude vs. size with some histograms and a scatter plot.</p>
<div class="sourceCode" id="cb156"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb156-1"><a href="correlation-and-simple-linear-regression.html#cb156-1" tabindex="-1"></a><span class="fu">hist</span>(pie_crab<span class="sc">$</span>latitude)</span></code></pre></div>
<p><img src="06-corr-slr_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<div class="sourceCode" id="cb157"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb157-1"><a href="correlation-and-simple-linear-regression.html#cb157-1" tabindex="-1"></a><span class="fu">hist</span>(pie_crab<span class="sc">$</span>size)</span></code></pre></div>
<p><img src="06-corr-slr_files/figure-html/unnamed-chunk-7-2.png" width="672" /></p>
<p>It is clear that crab data was surveyed at only a finite number of locations, which leads to a non-normal distribution. But that’s okay - linear regression does NOT require the variables to be normally distributed. However, the error of the data must be normally distributed around the linear line (more on error later).</p>
<p>When plotting, it is important to have the predictor variable on the x-axis, and the response variable on the y-axis. Then, we can fit a linear regression line through this data so that the distance between the line and the most observations is at its lowest:</p>
<div class="sourceCode" id="cb158"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb158-1"><a href="correlation-and-simple-linear-regression.html#cb158-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> pie_crab, <span class="fu">aes</span>(<span class="at">x =</span> latitude, <span class="at">y =</span> size)) <span class="sc">+</span> </span>
<span id="cb158-2"><a href="correlation-and-simple-linear-regression.html#cb158-2" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb158-3"><a href="correlation-and-simple-linear-regression.html#cb158-3" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb158-4"><a href="correlation-and-simple-linear-regression.html#cb158-4" tabindex="-1"></a>  <span class="fu">theme_bw</span>() </span></code></pre></div>
<p><img src="06-corr-slr_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>Each observation’s vertical distance away from the line is the observation’s <strong>error</strong>. Getting the standard deviation of these distances gives us the line’s <strong>residual standard error</strong>.</p>
<p>The intercept of this line, or the value of the line if we extended it out to meet the y-axis (i.e., where our crab size is zero), is also known as the line’s <strong>constant</strong>.</p>
<p>Lastly, we have our <strong>slope</strong> of the line. This tells us how much a crab’s average size increases if we increase the latitude, and vice versa.</p>
<p>When we put all of these pieces together, we get the following <strong>simple linear regression equation for each observation</strong>:</p>
<p>size = slope of the line * latitude + constant + point’s distance from line</p>
<p>… which we write statistically as:</p>
<p><span class="math inline">\(y = (β1 * x) + β0 + ε\)</span></p>
<p>In this equation, <em>y</em> is a our response variable (crab’s size), β0 is the constant, β1 is the slope, x is our explanatory variable (the crab’s latitude), and ε is the distance between the line and each observation’s true size.</p>
<div id="simple-linear-regression-in-r" class="section level4 hasAnchor" number="7.2.0.1">
<h4><span class="header-section-number">7.2.0.1</span> Simple linear regression in R<a href="correlation-and-simple-linear-regression.html#simple-linear-regression-in-r" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>In R, we can identify the values that go into delineating this line of best fit using the base R {stats} package’s <code>lm()</code> function (lm for linear model):</p>
<div class="sourceCode" id="cb159"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb159-1"><a href="correlation-and-simple-linear-regression.html#cb159-1" tabindex="-1"></a><span class="co"># Simple linear regression model</span></span>
<span id="cb159-2"><a href="correlation-and-simple-linear-regression.html#cb159-2" tabindex="-1"></a>slr_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(size <span class="sc">~</span> latitude, <span class="at">data =</span> pie_crab) <span class="co"># lm(response ~ predictor, data = dataset)</span></span>
<span id="cb159-3"><a href="correlation-and-simple-linear-regression.html#cb159-3" tabindex="-1"></a></span>
<span id="cb159-4"><a href="correlation-and-simple-linear-regression.html#cb159-4" tabindex="-1"></a><span class="fu">summary</span>(slr_model)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = size ~ latitude, data = pie_crab)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -7.8376 -1.8797  0.1144  1.9484  6.9280 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -3.62442    1.27405  -2.845  0.00468 ** 
## latitude     0.48512    0.03359  14.441  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.832 on 390 degrees of freedom
## Multiple R-squared:  0.3484, Adjusted R-squared:  0.3467 
## F-statistic: 208.5 on 1 and 390 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>… where -3.62442 is our line’s intercept (β0), 0.48512 is our line’s slope (β1):</p>
<p><span class="math inline">\(y = 0.48512x - 3.62442\)</span></p>
<p>In the model’s summary, our p-value is indicated in the <code>Pr(&gt;|t|)</code> column for <code>latitude</code>: because our p-value is well below 0.05, we can deduce that latitude has a significant effect on crab size. Therefore, fiddler crabs appear to follow Bergmann’s rule: on average, crab size increased by 0.49 mm for every degree in latitude.</p>
</div>
<div id="predicting-crab-size" class="section level4 hasAnchor" number="7.2.0.2">
<h4><span class="header-section-number">7.2.0.2</span> Predicting crab size<a href="correlation-and-simple-linear-regression.html#predicting-crab-size" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>With this linear equation, we can now predict crab size at different latitudes using the base R <code>predict()</code> function.</p>
<p>Let’s predict crab size for latitudes of 32, 36, and 38 degrees. Note that we need to create these values as a new data frame with the same column name used in the data that the model was built off of (i.e., <code>latitude</code>):</p>
<div class="sourceCode" id="cb161"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb161-1"><a href="correlation-and-simple-linear-regression.html#cb161-1" tabindex="-1"></a>new_lat <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">latitude =</span> <span class="fu">c</span>(<span class="dv">32</span>, <span class="dv">36</span>, <span class="dv">38</span>))</span>
<span id="cb161-2"><a href="correlation-and-simple-linear-regression.html#cb161-2" tabindex="-1"></a></span>
<span id="cb161-3"><a href="correlation-and-simple-linear-regression.html#cb161-3" tabindex="-1"></a><span class="fu">predict</span>(slr_model, <span class="at">newdata =</span> new_lat)</span></code></pre></div>
<pre><code>##        1        2        3 
## 11.89939 13.83987 14.81010</code></pre>
</div>
</div>
<div id="assignment" class="section level2 hasAnchor" number="7.3">
<h2><span class="header-section-number">7.3</span> Assignment:<a href="correlation-and-simple-linear-regression.html#assignment" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>For this week’s exercise, we will be using the <code>ntl_airtemp</code> and <code>ntl_icecover</code> data sets to explore the relationship between mean annual lake ice duration and mean winter air temperature at two nearby lakes in Wisconsin. <code>ntl_airtemp</code> contains daily estimates of the air temperature near the two lakes. <code>ntl_icecover</code> contains the duration of ice cover per year, per lake.</p>
<div class="sourceCode" id="cb163"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb163-1"><a href="correlation-and-simple-linear-regression.html#cb163-1" tabindex="-1"></a><span class="fu">data</span>(<span class="st">&quot;ntl_airtemp&quot;</span>)</span>
<span id="cb163-2"><a href="correlation-and-simple-linear-regression.html#cb163-2" tabindex="-1"></a><span class="fu">data</span>(<span class="st">&quot;ntl_icecover&quot;</span>)</span></code></pre></div>
<p>First, let’s get the average lake ice duration across years:</p>
<div class="sourceCode" id="cb164"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb164-1"><a href="correlation-and-simple-linear-regression.html#cb164-1" tabindex="-1"></a>avg_icecover <span class="ot">&lt;-</span> ntl_icecover <span class="sc">%&gt;%</span></span>
<span id="cb164-2"><a href="correlation-and-simple-linear-regression.html#cb164-2" tabindex="-1"></a>  <span class="co"># mutate within group by, and create a new variable for the WATER year (Oct - Sept). Water year is the FUTURE year so we do year + 1</span></span>
<span id="cb164-3"><a href="correlation-and-simple-linear-regression.html#cb164-3" tabindex="-1"></a>  <span class="fu">group_by</span>(<span class="at">wyear =</span> year <span class="sc">+</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb164-4"><a href="correlation-and-simple-linear-regression.html#cb164-4" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean_duration =</span> <span class="fu">mean</span>(ice_duration, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span></code></pre></div>
<p>Next, we will need to compute the mean winter (November-April) air temperature per <em>water year</em> to align with the data in <code>avg_icecover</code>. A <em>water year</em> is a 12-month period starting in October and ending in September, aligning with the winter season and thereby not splitting up the winter.</p>
<p>Let’s first define each date’s water year using an <code>if_else()</code> statement and the <code>month()</code> function from the {lubridate} package:</p>
<div class="sourceCode" id="cb165"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb165-1"><a href="correlation-and-simple-linear-regression.html#cb165-1" tabindex="-1"></a>ntl_airtemp_wyear <span class="ot">&lt;-</span> ntl_airtemp <span class="sc">%&gt;%</span></span>
<span id="cb165-2"><a href="correlation-and-simple-linear-regression.html#cb165-2" tabindex="-1"></a>  <span class="co"># Add a column to group the Fall and Spring season into a same year </span></span>
<span id="cb165-3"><a href="correlation-and-simple-linear-regression.html#cb165-3" tabindex="-1"></a>  <span class="co"># (similar to hydrologic &quot;water years&quot;) using the lubridate package:</span></span>
<span id="cb165-4"><a href="correlation-and-simple-linear-regression.html#cb165-4" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">wyear =</span> <span class="fu">if_else</span>(<span class="fu">month</span>(sampledate) <span class="sc">&lt;</span> <span class="dv">10</span>, year, year<span class="sc">+</span><span class="dv">1</span>))</span></code></pre></div>
<p>Next, using <code>ntl_airtemp_wyear</code>, we can compute the average air temperature for the winter season per water year.</p>
<div class="sourceCode" id="cb166"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb166-1"><a href="correlation-and-simple-linear-regression.html#cb166-1" tabindex="-1"></a>ntl_winter_airtemp <span class="ot">&lt;-</span> ntl_airtemp_wyear <span class="sc">%&gt;%</span></span>
<span id="cb166-2"><a href="correlation-and-simple-linear-regression.html#cb166-2" tabindex="-1"></a>  <span class="fu">filter</span>(lubridate<span class="sc">::</span><span class="fu">month</span>(sampledate) <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">11</span>, <span class="dv">12</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>)) <span class="sc">%&gt;%</span> <span class="co"># filter the months from Nov to April</span></span>
<span id="cb166-3"><a href="correlation-and-simple-linear-regression.html#cb166-3" tabindex="-1"></a>  <span class="fu">group_by</span>(wyear) <span class="sc">%&gt;%</span></span>
<span id="cb166-4"><a href="correlation-and-simple-linear-regression.html#cb166-4" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean_air_temp =</span> <span class="fu">mean</span>(ave_air_temp_adjusted))</span></code></pre></div>
<div id="e1-join-your-table-of-water-yearly-average-winter-temperatures-to-our-avg_icecover-object.-save-this-new-table-as-icecover_temp.-hint-use-a-join-function-to-do-this." class="section level4 hasAnchor" number="7.3.0.1">
<h4><span class="header-section-number">7.3.0.1</span> E1: Join your table of (water-)yearly average winter temperatures to our <code>avg_icecover</code> object. Save this new table as <code>icecover_temp</code>. (HINT: use a <code>join()</code> function to do this.)<a href="correlation-and-simple-linear-regression.html#e1-join-your-table-of-water-yearly-average-winter-temperatures-to-our-avg_icecover-object.-save-this-new-table-as-icecover_temp.-hint-use-a-join-function-to-do-this." class="anchor-section" aria-label="Anchor link to header"></a></h4>
</div>
<div id="e2-visualize-the-data-by-plotting-our-variables-against-one-another-and-using-histograms.-is-their-relationship-linear-are-our-variables-normally-distributed" class="section level4 hasAnchor" number="7.3.0.2">
<h4><span class="header-section-number">7.3.0.2</span> E2: Visualize the data by plotting our variables against one another, and using histograms. Is their relationship linear? Are our variables normally distributed?<a href="correlation-and-simple-linear-regression.html#e2-visualize-the-data-by-plotting-our-variables-against-one-another-and-using-histograms.-is-their-relationship-linear-are-our-variables-normally-distributed" class="anchor-section" aria-label="Anchor link to header"></a></h4>
</div>
<div id="e3-perform-a-correlation-test-on-icecover_temp-to-see-whether-there-is-a-significant-relationship-between-mean-ice-duration-and-mean-air-temperature.-what-is-the-test-statistic-of-this-relationship-is-the-relationship-positive-or-negative" class="section level4 hasAnchor" number="7.3.0.3">
<h4><span class="header-section-number">7.3.0.3</span> E3: Perform a correlation test on <code>icecover_temp</code> to see whether there is a significant relationship between mean ice duration and mean air temperature. What is the test statistic of this relationship? Is the relationship positive or negative?<a href="correlation-and-simple-linear-regression.html#e3-perform-a-correlation-test-on-icecover_temp-to-see-whether-there-is-a-significant-relationship-between-mean-ice-duration-and-mean-air-temperature.-what-is-the-test-statistic-of-this-relationship-is-the-relationship-positive-or-negative" class="anchor-section" aria-label="Anchor link to header"></a></h4>
</div>
<div id="e4-use-a-simple-linear-model-to-predict-the-mean-ice-duration-for-a-year-whose-mean-temperature-is--2-degrees-0-degrees-and-2-degrees." class="section level4 hasAnchor" number="7.3.0.4">
<h4><span class="header-section-number">7.3.0.4</span> E4: Use a simple linear model to predict the mean ice duration for a year whose mean temperature is -2 degrees, 0 degrees, and 2 degrees.<a href="correlation-and-simple-linear-regression.html#e4-use-a-simple-linear-model-to-predict-the-mean-ice-duration-for-a-year-whose-mean-temperature-is--2-degrees-0-degrees-and-2-degrees." class="anchor-section" aria-label="Anchor link to header"></a></h4>
</div>
<div id="e5-plot-the-average-air-temperature-against-the-average-ice-cover-duration.-include-our-simple-linear-regression-i.e.-the-line-of-best-fit-in-the-plot." class="section level4 hasAnchor" number="7.3.0.5">
<h4><span class="header-section-number">7.3.0.5</span> E5: Plot the average air temperature against the average ice cover duration. Include our simple linear regression (i.e., the line of best fit) in the plot.<a href="correlation-and-simple-linear-regression.html#e5-plot-the-average-air-temperature-against-the-average-ice-cover-duration.-include-our-simple-linear-regression-i.e.-the-line-of-best-fit-in-the-plot." class="anchor-section" aria-label="Anchor link to header"></a></h4>
</div>
<div id="e6-what-are-the-slope-intercept-and-the-residual-standard-error-of-our-simple-linear-regression-line" class="section level4 hasAnchor" number="7.3.0.6">
<h4><span class="header-section-number">7.3.0.6</span> E6: What are the slope, intercept, and the residual standard error of our simple linear regression line?<a href="correlation-and-simple-linear-regression.html#e6-what-are-the-slope-intercept-and-the-residual-standard-error-of-our-simple-linear-regression-line" class="anchor-section" aria-label="Anchor link to header"></a></h4>

<div class="sourceCode" id="cb167"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb167-1"><a href="correlation-and-simple-linear-regression.html#cb167-1" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb167-2"><a href="correlation-and-simple-linear-regression.html#cb167-2" tabindex="-1"></a><span class="fu">library</span>(lterdatasampler)</span></code></pre></div>
</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="data-analysis-t-test-and-anova.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="multiple-linear-regression-mlr.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/USERNAME/REPO/edit/BRANCH/06-corr-slr.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["_main.pdf", "_main.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
